apiVersion: v1
kind: Pod
metadata:
  namespace: kube-ops
spec:
  containers:
    - name: jnlp
      image: "jenkins/inbound-agent:latest"
      workingDir: "/home/jenkins/agent"
    - name: docker
      image: "docker:27.3.1-dind-alpine3.20"
      volumeMounts:
        - name: "workspace"
          readOnly: false
          mountPath: /home/jenkins/agent
      workingDir: "/home/jenkins/agent"
  volumes:
    - name: "workspace"
      persistentVolumeClaim:
        claimName: "jenkins-home-data"