apiVersion: v1
kind: Pod
metadata:
  namespace: kube-ops
spec:
  containers:
    - name: jnlp
      image: "jenkins/inbound-agent:latest"
      tty: true
    - name: docker
      image: "docker:27.3.1-dind"
      securityContext:
        privileged: true
      tty: true
  volumes:
    - name: "workspace"
      persistentVolumeClaim:
        claimName: "jenkins-home-data"